### ISSUE TITLE
Move Token

### ISSUE THREAD

**Issue by pavanin** [STEP-tw/cluedo-brainyfools#11]
As a _player_

I want to _move my token_

So that I can _change my position on the board_

**Additional Details**

- Assumptions:
  -  _selected a position to move_
  -  _rolled the dice first_
  -  _it is my turn_

**Acceptance Criteria**

- [x] Criteria 1
  - Given _I have selected a valid position_
  - When _I move my token to that position_
  - Then _my position should get changed_

- [x] Criteria 2
  - Given _I have moved token in the current turn_
  - When _I tried to move it again_
  - Then _I shouldn't be able to move it again_

- [x] Criteria 3
  - Given _I have selected an invalid position_
  - When _I move my token to that position_
  - Then _my position should not get changed_

**Comment by Raghunathssj** [comment]
Show message to player, if player made invalid move
