### ISSUE TITLE
Join Game

### ISSUE THREAD

**Issue by devilk10** [STEP-tw/cluedo-brainyfools#2]
As a _player_

I want to _join a game_

So that _I can play with the players who have already joined the game_

**Acceptance Criteria**

- [x] Criteria 1
  - Given _I have place to enter a game ID_
  - When _I have entered a valid game ID_
  - Then _I can put my name and select my character_
- [x] Criteria 2
  - Given _I have place to enter a game ID_
  - When _I have entered an invalid game ID_
  - Then _I should not be able to put my name and select my character_

**Comment by Raghunathssj** [comment]
while informing player with message in `join game` (i.e., while showing `invalid game id`) it should not change tab to `create game` it should stay in `join game` tab.
